<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="COS20031 Assignment">
        <meta name="keywords" content="Job Test Application">
        <meta name="author" content="Group 2 - COS20031">
        <link href="./styles/style.css" rel="stylesheet">
        <link rel="icon" type="image/x-icon" href="./images/logo.ico">
        <title><?php echo $GLOBALS['title']?></title>
    </head>
</html>